# Generated by Django 3.1.2 on 2020-11-06 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20201105_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
